export const level = {
  name: "connected-room-template",
  title: "Connected Rooms",
  objective: "Walk the house. Use doors to change floors.",
  background: { url: "", width: 1000, height: 1000 },
  bounds: {
    width: 1000,
    height: 1000,
    walkMin: 15,
    walkMax: 985,
    enterRightX: 850,
  },
  camera: { followZoom: 1, overlayZoom: 1.35, maxZoom: 1.6 },
  audio: {
    music: "",
    sfx: [],
    dialogue: [],
  },
  player: { width: 56, height: 96 },
  floors: [
    {
      floor: 1,
      name: "Lower",
      bbox: [0, 800, 1000, 850],
      groundY: 820,
      spawn: { x: 120, y: 724 },
      objective: "Walk right and use the door.",
    },
    {
      floor: 2,
      name: "Upper",
      bbox: [0, 400, 1000, 450],
      groundY: 420,
      spawn: { x: 120, y: 324 },
      objective: "Explore the upper floor.",
    },
  ],
  platforms: [
    { id: "floor-1", x: 0, y: 800, w: 1000, h: 50 },
    { id: "floor-2", x: 0, y: 400, w: 1000, h: 50 },
  ],
  walls: [],
  hazards: [],
  doors: [
    {
      id: "door-f1-right",
      pair: "door-main",
      floor: 1,
      x: 907,
      y: 700,
      w: 61,
      h: 120,
      toFloor: 2,
      toSide: "left",
      forward: true,
    },
    {
      id: "door-f2-left",
      pair: "door-main",
      floor: 2,
      x: 39,
      y: 290,
      w: 58,
      h: 130,
      toFloor: 1,
      toSide: "right",
    },
  ],
  instances: [
    {
      id: "player",
      floor: 1,
      x: 120,
      y: 724,
      w: 56,
      h: 96,
      facing: 1,
    },
  ],
  collectibles: [],
  enemies: [],
  patrols: {},
  goal: null,
  introShots: [
    {
      floor: 2,
      x: 500,
      zoom: 2.5,
      move: 0,
      hold: 0.45,
      ease: "outCubic",
      caption: { kicker: "The house", title: "Upper" },
    },
    {
      floor: 1,
      x: 220,
      zoom: 2.5,
      move: 1.2,
      hold: 0.4,
      ease: "inOutCubic",
    },
    {
      player: true,
      zoom: 2.45,
      move: 1.05,
      hold: 0.35,
      ease: "inOutCubic",
    },
    {
      follow: true,
      move: 0.9,
      hold: 0.1,
      ease: "inOutCubic",
      caption: { kicker: "", title: "" },
    },
  ],
  assets: [],
};

export const assetById = new Map(
  level.assets.map((asset) => [asset.id, asset]),
);
export const floorById = new Map(
  level.floors.map((floor) => [floor.floor, floor]),
);
